name: generate

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  first:
    name: test
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Install Dependencies
        run: |
          yarn
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
